version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017

  books:
    build: ./Books
    restart: always
    container_name: books
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017/
    ports:
      - "5001:5001"
    expose:
      - 5001

  loans_1:
    build: ./Loans
    restart: always
    container_name: loans_1
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017/
      PORT: 5002
    ports:
      - "5002:5002"
    expose:
      - 5002

  loans_2:
    build: ./Loans
    restart: always
    container_name: loans_2
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017/
      PORT: 5003
    ports:
      - "5003:5003"
    expose:
      - 5003

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - books
      - loans_1
      - loans_2
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

